### ISSUE TITLE
ActionView::MissingTemplate (Missing template park/index_stream ...

### ISSUE THREAD

**Issue by kirantpatil** [acdesouza/rails-and-server-sent-events#4]
Hi,

I am using your code in my app and I am getting below error:

tarted GET "/user_stream" for 127.0.0.1 at 2015-06-11 13:17:42 +0530
Processing by ParkController#index_stream as text/event-stream
  Event Load (0.3ms)  SELECT  "events".* FROM "events"  ORDER BY updated_at DESC, created_at DESC LIMIT 1
Completed 500 Internal Server Error in 5ms (ActiveRecord: 0.3ms)

ActionView::MissingTemplate (Missing template park/index_stream, application/index_stream with {:locale=>[:en], :formats=>["text/event-stream"], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder]}. Searched in:
  * "/home/kpatil/work/nagaraj/svg_nload/app/views"
):
  actionview (4.2.1) lib/action_view/path_set.rb:46:in `find'
  actionview (4.2.1) lib/action_view/lookup_context.rb:121:in `find'
  actionview (4.2.1) lib/action_view/renderer/abstract_renderer.rb:18:in `find_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:40:in `determine_template'
  actionview (4.2.1) lib/action_view/renderer/template_renderer.rb:8:in `render'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.1) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.1) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.1) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.1) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /home/kpatil/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
  activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
  actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
  activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action

**Comment by kirantpatil** [comment]
It worked after  adding this line "render nothing: true"
